"source ~/.vim/plugin.vim
set nu
set cindent
set smartindent
filetype plugin indent on
set hlsearch
set showmatch
color koehler
set completeopt=preview,menu
"set ruler
"set nocompatible
syntax on
set tabstop=4
set shiftwidth=4
set incsearch
set ignorecase smartcase
 
"ctags
set autochdir
set tags=tags;
 
"Open file at the last position
au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif
 
"Taglist
let Tlist_Ctags_Cmd = '~/bin/ctags'
let Tlist_Show_One_File=1
let Tlist_Exit_OnlyWindow=1
let Tlist_Use_Right_Window = 1
let Tlist_Use_SingleClick= 1
let Tlist_Process_File_Always=1
let Tlist_File_Fold_Auto_Close=1
let Tlist_Auto_Open=1
let Tlist_Auto_Highlight_Tag=1
let Tlist_Auto_Update=1
 
"Syntastic
"set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*
"let g:syntastic_always_populate_loc_list = 1
"let g:syntastic_auto_loc_list = 1
"let g:syntastic_check_on_open = 1
"let g:syntastic_check_on_wq = 0

filetype plugin indent on

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

call vundle#end()            " required
filetype plugin indent on    " required

filetype plugin on
